# Generated by Django 5.1.2 on 2025-09-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_headline', models.CharField(max_length=250)),
                ('hero_subcopy', models.TextField(blank=True)),
                ('hero_media_url', models.URLField(blank=True)),
                ('stat_projects', models.CharField(default='650+', max_length=20)),
                ('stat_years', models.CharField(default='20+', max_length=20)),
                ('stat_specialists', models.CharField(default='1000+', max_length=20)),
                ('pinned_heading', models.CharField(blank=True, max_length=200)),
                ('pinned_title', models.CharField(blank=True, max_length=250)),
                ('pinned_body_1', models.TextField(blank=True)),
                ('pinned_body_2', models.TextField(blank=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=70)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160)),
                ('canonical_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEditorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_images', to='myApp.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-seedling', max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='myApp.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_url', models.URLField()),
                ('full_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='myApp.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
