# Generated by Django 5.1.2 on 2025-09-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='insights_heading',
            field=models.CharField(blank=True, help_text='Heading for Insights block on this service page.', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='insights_subcopy',
            field=models.CharField(blank=True, help_text='Short description under the Insights heading.', max_length=300),
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('excerpt', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(blank=True)),
                ('read_minutes', models.PositiveSmallIntegerField(default=4)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='myApp.service')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
