# Generated by Django 5.1.1 on 2025-10-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_service_options_service_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('hero_image_url', models.URLField(help_text='Cloudinary URL for the featured banner image')),
                ('summary', models.TextField(blank=True, help_text='Short teaser for the projects section')),
                ('scope', models.CharField(blank=True, default='Design + Build', max_length=100)),
                ('size_label', models.CharField(blank=True, default='', max_length=100)),
                ('timeline_label', models.CharField(blank=True, default='', max_length=100)),
                ('status_label', models.CharField(blank=True, default='Completed', max_length=100)),
                ('tags_csv', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('cta_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='myApp.service')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order', 'title'],
            },
        ),
    ]
