# Generated by Django 5.1.1 on 2025-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_teammember'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teammember',
            name='myApp_teamm_is_acti_12388e_idx',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Cloudinary (or any) image URL'),
        ),
    ]
