# Generated by Django 5.1.1 on 2025-10-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_teammember_myapp_teamm_is_acti_12388e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cld_folder', models.CharField(blank=True, help_text="Cloudinary folder (e.g., projects/dubai_hills). If blank, uses 'uploads'.", max_length=200)),
                ('default_tags', models.CharField(blank=True, help_text='CSV tags to apply to assets uploaded through Admin.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=240)),
                ('secure_url', models.URLField(blank=True, help_text='Original delivery URL (secure)')),
                ('web_url', models.URLField(blank=True, help_text='f_auto,q_auto variant for web use')),
                ('thumb_url', models.URLField(blank=True, help_text='Small thumbnail variant')),
                ('bytes_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('tags_csv', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='myApp.mediaalbum')),
            ],
            options={
                'ordering': ['album__title', 'sort_order', 'title'],
            },
        ),
    ]
