# Generated by Django 5.1.2 on 2025-10-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_mediaalbum_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='blocks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='myApp.insight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
