# Generated by Django 5.1.2 on 2025-10-06 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_insight_blocks_contentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive insights are not shown in public views'),
        ),
        migrations.CreateModel(
            name='InsightAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', 'Delete'), ('create', 'Create'), ('update', 'Update'), ('activate', 'Activate'), ('deactivate', 'Deactivate')], max_length=20)),
                ('insight_id', models.PositiveIntegerField(help_text='ID of the insight (may be deleted)')),
                ('insight_slug', models.SlugField(blank=True, help_text='Slug of the insight', max_length=220)),
                ('insight_title', models.CharField(help_text='Title of the insight', max_length=200)),
                ('actor_username', models.CharField(blank=True, help_text='Username at time of action', max_length=150)),
                ('actor_email', models.EmailField(blank=True, help_text='Email at time of action', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='myApp_insig_action_ae3aa4_idx'), models.Index(fields=['actor', 'timestamp'], name='myApp_insig_actor_i_f0cff3_idx'), models.Index(fields=['timestamp'], name='myApp_insig_timesta_2005e2_idx')],
            },
        ),
    ]
