# Generated by Django 5.1.2 on 2025-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_add_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
