# Generated by Django 5.1.2 on 2025-10-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_increase_seo_meta_description_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprojectimage',
            name='case_study',
            field=models.ForeignKey(blank=True, help_text='Link to case study detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='myApp.casestudy'),
        ),
    ]
