# Generated by Django 5.1.2 on 2025-10-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_add_case_study_link_to_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='completion_date',
            field=models.DateField(blank=True, help_text='When was the project completed?', null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True, help_text='Full project description and story'),
        ),
    ]
