# Generated by Django 5.1.2 on 2025-10-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_add_description_and_completion_date_to_case_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='full_url',
            field=models.URLField(blank=True, help_text='Full resolution image'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='thumb_url',
            field=models.URLField(blank=True, help_text='Thumbnail for service page gallery'),
        ),
        migrations.AlterField(
            model_name='serviceprojectimage',
            name='case_study',
            field=models.ForeignKey(blank=True, help_text='Legacy field - images now in CaseStudy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_images', to='myApp.casestudy'),
        ),
        migrations.AlterField(
            model_name='serviceprojectimage',
            name='full_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprojectimage',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
    ]
