# Generated by Django 5.1.2 on 2025-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_consolidate_projects_add_images_to_case_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='gallery_urls',
            field=models.JSONField(blank=True, default=list, help_text='Array of gallery image objects with full and thumb URLs'),
        ),
    ]
