# Generated by Django 5.1.2 on 2025-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_add_image_position_to_pagehero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='image_position',
            field=models.CharField(default='50% 50%', help_text="CSS background-position (e.g., '50% 50%', '50% 30%')", max_length=50),
        ),
    ]
