# Generated by Django 5.1.2 on 2025-10-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_alter_pagehero_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_image_position',
            field=models.CharField(default='50% 40%', help_text="CSS background-position for hero image (e.g., '50% 40%')", max_length=50),
        ),
    ]
