# Generated by Django 5.1.2 on 2025-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_set_default_hero_image_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_cropped_url',
            field=models.URLField(blank=True, help_text='Cropped hero image (21:9 aspect ratio)'),
        ),
    ]
