# Generated by Django 5.1.2 on 2025-10-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_add_cropped_hero_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured_case_study',
            field=models.ForeignKey(blank=True, help_text='Select which project will be featured on the landing page for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_service', to='myApp.casestudy'),
        ),
    ]
