# Generated by Django 5.1.2 on 2025-11-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_service_featured_case_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text="URL path (e.g., '/about/', '/projects/', '/landscape/')", max_length=500, unique=True)),
                ('page_name', models.CharField(help_text='Human-readable name for this page', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO (max 140 characters recommended)', max_length=140)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO (max 200 characters)', max_length=200)),
                ('meta_keywords', models.CharField(blank=True, help_text='Optional keywords (comma-separated)', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=140)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description for social sharing', max_length=200)),
                ('og_image', models.URLField(blank=True, help_text='Open Graph image URL for social sharing')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Metadata',
                'verbose_name_plural': 'Pages Metadata',
                'ordering': ['url_path'],
            },
        ),
    ]
