# Generated by Django 5.1.2 on 2025-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_pagemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Why this email was blocked', max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Blocked Email',
                'verbose_name_plural': 'Blocked Emails',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Why this IP was blocked', max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('message_preview', models.CharField(blank=True, help_text='First 200 chars of message', max_length=200)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email', 'submitted_at'], name='myApp_forms_email_360156_idx'), models.Index(fields=['ip_address', 'submitted_at'], name='myApp_forms_ip_addr_99685b_idx')],
            },
        ),
    ]
