# Generated by Django 5.1.2 on 2026-02-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_increase_pagemetadata_field_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Job title/position name', max_length=200)),
                ('department', models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Interior & Fit-Out', 'Interior & Fit-Out'), ('FM', 'FM'), ('Admin', 'Admin'), ('Finance', 'Finance'), ('Sales', 'Sales')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Job description and requirements')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this position currently open?')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('visa_status', models.CharField(blank=True, choices=[('', 'Select Visa Status'), ('Visit Visa', 'Visit Visa'), ('Employment Visa', 'Employment Visa'), ('Residence Visa', 'Residence Visa'), ('Student Visa', 'Student Visa'), ('No Visa', 'No Visa'), ('Other', 'Other')], max_length=50)),
                ('position_custom', models.CharField(blank=True, help_text='Custom position if not in dropdown', max_length=200)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('notice_period', models.CharField(max_length=100)),
                ('expected_salary_aed', models.CharField(blank=True, max_length=50)),
                ('cv_resume', models.FileField(help_text='Upload CV/Resume (PDF/DOC)', upload_to='job_applications/cvs/')),
                ('portfolio_link', models.URLField(blank=True, help_text='Portfolio link or upload')),
                ('portfolio_file', models.FileField(blank=True, help_text='Portfolio file upload (optional)', null=True, upload_to='job_applications/portfolios/')),
                ('why_work_with_us', models.TextField(blank=True, help_text='Why do you want to work with us?')),
                ('relevant_experience', models.TextField(blank=True, help_text='Relevant experience or key project')),
                ('information_accurate', models.BooleanField(default=False, help_text='I confirm the information provided is accurate')),
                ('data_processing_consent', models.BooleanField(default=False, help_text='I consent to data processing for recruitment purposes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the candidate')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('position_applied_for', models.ForeignKey(blank=True, help_text='Position from dropdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='myApp.jobposting')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='myApp_jobap_email_f65095_idx'), models.Index(fields=['status', '-created_at'], name='myApp_jobap_status_1b5953_idx')],
            },
        ),
    ]
